spring:
  application:
    name: role-service
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

  grpc:
    server:
      port: 9090
      ssl:
        enabled: true
        client-auth: require
        bundle: lokit-role-server-ssl

    client:
      channel:
        identity-service:
          target: static://localhost:9095
          ssl:
            enabled: true
            bundle: lokit-role-client-ssl

  ssl:
    bundle:
      jks:
        lokit-role-server-ssl:
          keystore.location: classpath:role-server-keystore.p12
          keystore.password: changeit
          keystore.type: PKCS12
          truststore.location: classpath:role-server-truststore.p12
          truststore.password: changeit
          truststore.type: PKCS12
        lokit-role-client-ssl:
          keystore.location: classpath:role-client-keystore.p12
          keystore.password: changeit
          keystore.type: PKCS12
          truststore.location: classpath:role-client-truststore.p12
          truststore.password: changeit
          truststore.type: PKCS12

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/lokit
          jwk-set-uri: http://localhost:8090/realms/lokit/protocol/openid-connect/certs

server:
  port: 8080

lokit:
  jwt:
    role-claims:
      - realm_access.roles