spring:
  application:
    name: decision-service

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

  grpc:
    client:
      channel:
        role-service:
          target: static://localhost:9090
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl
        room-service:
          target: static://localhost:9091
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl
        card-service:
          target: static://localhost:9092
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl
        device-service:
          target: static://localhost:9093
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl

  ssl:
    bundle:
      jks:
        lokit-decision-client-ssl:
          keystore.location: classpath:decision-client-keystore.p12
          keystore.password: changeit
          keystore.type: PKCS12
          truststore.location: classpath:decision-client-truststore.p12
          truststore.password: changeit
          truststore.type: PKCS12

server:
  port: 8084

logging:
  level:
    ovh.eukon05.lokit.decisionservice: debug
