spring:
  application:
    name: decision-service

  data:
    redis:
      host: ${LOKIT_REDIS_HOST}
      port: ${LOKIT_REDIS_PORT}

  rabbitmq:
    username: ${LOKIT_RABBITMQ_USERNAME}
    password: ${LOKIT_RABBITMQ_PASSWORD}
    host: ${LOKIT_RABBITMQ_HOST}
    port: ${LOKIT_RABBITMQ_PORT}

  grpc:
    client:
      channel:
        role-service:
          target: ${LOKIT_ROLE_GRPC_TARGET}
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl
        room-service:
          target: ${LOKIT_ROOM_GRPC_TARGET}
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl
        card-service:
          target: ${LOKIT_CARD_GRPC_TARGET}
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl
        device-service:
          target: ${LOKIT_DEVICE_GRPC_TARGET}
          ssl:
            enabled: true
            bundle: lokit-decision-client-ssl

  ssl:
    bundle:
      jks:
        lokit-decision-client-ssl:
          keystore.location: classpath:decision-client-keystore.p12
          keystore.password: ${LOKIT_DECISION_TLS_CLIENT_KEYSTORE_PASSWORD}
          keystore.type: PKCS12
          truststore.location: classpath:decision-client-truststore.p12
          truststore.password: ${LOKIT_DECISION_TLS_CLIENT_TRUSTSTORE_PASSWORD}
          truststore.type: PKCS12

eureka:
  client:
    service-url:
      defaultZone: ${LOKIT_EUREKA_HOST}:${LOKIT_EUREKA_PORT}/eureka
  instance:
    prefer-ip-address: true

server:
  port: ${LOKIT_DECISION_PORT}

logging:
  level:
    ovh.eukon05.lokit.decisionservice: debug
