spring:
  application:
    name: device-service
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  grpc:
    client:
      channel:
        room-service:
          target: static://localhost:9091
          ssl:
            enabled: true
            bundle: lokit-device-client-ssl
    server:
      port: 9093
      ssl:
        enabled: true
        client-auth: require
        bundle: lokit-device-server-ssl

  ssl:
    bundle:
      jks:
        lokit-device-server-ssl:
          keystore.location: classpath:device-server-keystore.p12
          keystore.password: changeit
          keystore.type: PKCS12
          truststore.location: classpath:device-server-truststore.p12
          truststore.password: changeit
          truststore.type: PKCS12
        lokit-device-client-ssl:
          keystore.location: classpath:device-client-keystore.p12
          keystore.password: changeit
          keystore.type: PKCS12
          truststore.location: classpath:device-client-truststore.p12
          truststore.password: changeit
          truststore.type: PKCS12

  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/lokit
          jwk-set-uri: http://localhost:8090/realms/lokit/protocol/openid-connect/certs

server:
  port: 8083
